name: flolio

on:

   push:
     branches: [ master ]
      

jobs:

  deploy-to-server:
 
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        username: ans
        host: 68.183.88.222
        key: ${{ secrets.SSH_PASSWORD }}
        password: masterkey
        script: |
         cd /var/www/gymie
         git pull origin main
         git status

       
