name: flolio

on:

   push:
     branches: [ master ]
      

jobs:

  deploy-to-server:
 
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: 68.183.88.222
          REMOTE_USER: git
          REMOTE_PORT: 22
          TARGET: "/var/www/gymie"
          

       
